Bookstore.Catalog.Api/Bookstore.Web/Models/ErrorViewModel.cs
using System;

namespace Bookstore.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Bookstore.Catalog.Api/Bookstore.Web/Controllers/BooksController.cs
using Bookstore.Web.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bookstore.Web.Controllers
{
    public class BooksController : Controller
    {

        private BookCatalogService _bookCatalog;
        private OpenLibraryService _openLibrary;
        private EcontService _econtService;
        public BooksController(BookCatalogService bookCatalogService, OpenLibraryService openLibraryService, EcontService econtService)
        {
            _bookCatalog = bookCatalogService;
            _openLibrary = openLibraryService;
            _econtService = econtService;
        }
        public async Task<IActionResult> Index()
        {
            var books = await _bookCatalog.GetAllBooks();
            return View(books);
        }

        public async Task<IActionResult> Authors()
        {
            var authors = await _bookCatalog.GetAllAuthors();
            return View(authors);
        }

        public async Task<IActionResult> Author(int id)
        {
            var author = await _bookCatalog.GetAuthor(id);
            return View(author);
        }

        public async Task<IActionResult> Book(int id)
        {
            var book = await _bookCatalog.GetBook(id);
            var openLibraryBook = await _openLibrary.GetBookByISBN(book.ISBN);
            ViewBag.OpenLibraryBook = openLibraryBook;

            return View(book);
        }

        public async Task<IActionResult> BookPurchased(int id)
        {
            var book = await _bookCatalog.GetBook(id);
            var econtResponse = await _econtService.CreateLabel();
            return View("BookPurchased", econtResponse);
        }
    }
}

Bookstore.Catalog.Api/Bookstore.Web/Controllers/HomeController.cs
using Bookstore.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Bookstore.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Bookstore.Catalog.Api/Bookstore.Web/Views/Books/Author.cshtml
@model Bookstore.Catalog.Api.Dto.Books.AuthorResponse


    <h1>@Model.FirstName @Model.LastName</h1>
    <p>@Model.About</p>
    <p>Birth Year: @Model.BirthYear</p>
    <p>Nationality: @Model.Nationality</p>

    <ul>
        @foreach (var book in Model.Books)
        {
            <li><a asp-action="Book" asp-route-id="@book.BookID">@book.Title</a></li>
        }
    </ul>

Bookstore.Catalog.Api/Bookstore.Web/Views/Books/Authors.cshtml
@model List<Bookstore.Catalog.Api.Dto.Books.AuthorResponse>;


<ul>
    @foreach (var author in Model)
    {
        <li><a asp-action="Author" asp-route-id="@author.AuthorID">@author.FirstName @author.LastName</a></li>

    }
</ul>

Bookstore.Catalog.Api/Bookstore.Web/Views/Books/Book.cshtml
@model Bookstore.Catalog.Api.Dto.Books.BookResponse

<h1>@Model.Title</h1>
<p>ISBN: @Model.ISBN</p>
<p>@Model.Year</p>
<p>@Model.Price</p>

@if (@ViewBag.OpenLibraryBook != null)
{

    <p>Number of pages: @ViewBag.OpenLibraryBook.NumberOfPages</p>
    <img src="@ViewBag.OpenLibraryBook.Cover.Medium.ToString()" alt="" />
}


<form method="post" asp-action="BookPurchased">
    <input type="hidden" name="id" value="@Model.BookID" />
    <button type="submit" class="btn btn-primary">Purchase</button>
</form>

Bookstore.Catalog.Api/Bookstore.Web/Views/Books/BookPurchased.cshtml
@model Bookstore.Web.Econt.LabelResponse

    <p>Price of delivery: @Model.Label.TotalPrice лева</p>
    <p>Expected delivery date: @(DateTimeOffset.FromUnixTimeMilliseconds(Model.Label.ExpectedDeliveryDate.Value).DateTime.ToLongDateString())</p>

Bookstore.Catalog.Api/Bookstore.Web/Views/Books/Index.cshtml
@model List<Bookstore.Catalog.Api.Dto.Books.BookResponse>

@foreach (var book in Model)
{
  
    <h3>  <a asp-action="Book" asp-route-id="@book.BookID">@book.Title</a></h3>
    <p>@book.Price</p>
}

Bookstore.Catalog.Api/Bookstore.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Bookstore.Catalog.Api/Bookstore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookstore.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookstore.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Authors">Authors</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Bookstore.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>